// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clnxswsahpehitcgaxwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbnhzd3NhaHBlaGl0Y2dheHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTgyNDQsImV4cCI6MjA2Mzc3NDI0NH0.o8j6DUwMI-AggoaYSxQp4l_M7eFD_fnO3GLfCtODvc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);